/*
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ScalarOrVector;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateMatchTrialRequest
 */
public class CreateMatchTrialRequestTest {
    private final CreateMatchTrialRequest model = new CreateMatchTrialRequest();

    /**
     * Model tests for CreateMatchTrialRequest
     */
    @Test
    public void testCreateMatchTrialRequest() {
        // TODO: test CreateMatchTrialRequest
    }

    /**
     * Test the property 'variable'
     */
    @Test
    public void variableTest() {
        // TODO: test variable
    }

}
