/*
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Participant;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateSolutionResponse
 */
public class CreateSolutionResponseTest {
    private final CreateSolutionResponse model = new CreateSolutionResponse();

    /**
     * Model tests for CreateSolutionResponse
     */
    @Test
    public void testCreateSolutionResponse() {
        // TODO: test CreateSolutionResponse
    }

    /**
     * Test the property 'participant'
     */
    @Test
    public void participantTest() {
        // TODO: test participant
    }

    /**
     * Test the property 'trialNo'
     */
    @Test
    public void trialNoTest() {
        // TODO: test trialNo
    }

}
