/*
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.client.model.RunnerStatus;
import org.openapitools.client.model.ScalarOrVector;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MatchTrialEvaluation
 */
public class MatchTrialEvaluationTest {
    private final MatchTrialEvaluation model = new MatchTrialEvaluation();

    /**
     * Model tests for MatchTrialEvaluation
     */
    @Test
    public void testMatchTrialEvaluation() {
        // TODO: test MatchTrialEvaluation
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'objective'
     */
    @Test
    public void objectiveTest() {
        // TODO: test objective
    }

    /**
     * Test the property 'constraint'
     */
    @Test
    public void constraintTest() {
        // TODO: test constraint
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

    /**
     * Test the property 'feasible'
     */
    @Test
    public void feasibleTest() {
        // TODO: test feasible
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'finishedAt'
     */
    @Test
    public void finishedAtTest() {
        // TODO: test finishedAt
    }

}
