/*
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ScalarOrVector
 */
public class ScalarOrVectorTest {
    private final ScalarOrVector model = new ScalarOrVector();

    /**
     * Model tests for ScalarOrVector
     */
    @Test
    public void testScalarOrVector() {
        // TODO: test ScalarOrVector
    }

    /**
     * Test the property 'vector'
     */
    @Test
    public void vectorTest() {
        // TODO: test vector
    }

    /**
     * Test the property 'scalar'
     */
    @Test
    public void scalarTest() {
        // TODO: test scalar
    }

}
