/*
 * OptHub REST API
 * OptHubの公開REST APIです。
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.ParticipantType;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Solution
 */
public class SolutionTest {
    private final Solution model = new Solution();

    /**
     * Model tests for Solution
     */
    @Test
    public void testSolution() {
        // TODO: test Solution
    }

    /**
     * Test the property 'matchId'
     */
    @Test
    public void matchIdTest() {
        // TODO: test matchId
    }

    /**
     * Test the property 'participantType'
     */
    @Test
    public void participantTypeTest() {
        // TODO: test participantType
    }

    /**
     * Test the property 'participantId'
     */
    @Test
    public void participantIdTest() {
        // TODO: test participantId
    }

    /**
     * Test the property 'trialNo'
     */
    @Test
    public void trialNoTest() {
        // TODO: test trialNo
    }

    /**
     * Test the property 'variable'
     */
    @Test
    public void variableTest() {
        // TODO: test variable
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
