/*
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Authentication error code
 */
@JsonAdapter(AuthErrorCode.Adapter.class)
public enum AuthErrorCode {
  
  API_KEY_MISSING("APIKeyMissing"),
  
  INVALID_API_KEY("InvalidAPIKey");

  private String value;

  AuthErrorCode(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static AuthErrorCode fromValue(String value) {
    for (AuthErrorCode b : AuthErrorCode.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<AuthErrorCode> {
    @Override
    public void write(final JsonWriter jsonWriter, final AuthErrorCode enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public AuthErrorCode read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return AuthErrorCode.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    AuthErrorCode.fromValue(value);
  }
}

