/*
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.1.1
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Failed to retrieve the solution
 */
@JsonAdapter(GetSolutionError.Adapter.class)
public enum GetSolutionError {
  
  INVALID_MATCH_ID("InvalidMatchId"),
  
  INVALID_PARTICIPANT_ID("InvalidParticipantId"),
  
  TRIAL_NOT_FOUND("TrialNotFound");

  private String value;

  GetSolutionError(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static GetSolutionError fromValue(String value) {
    for (GetSolutionError b : GetSolutionError.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<GetSolutionError> {
    @Override
    public void write(final JsonWriter jsonWriter, final GetSolutionError enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public GetSolutionError read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return GetSolutionError.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    GetSolutionError.fromValue(value);
  }
}

