/*
 * OptHub REST API
 * OptHub Public REST API.
 *
 * The version of the OpenAPI document: 0.3.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Types of trial status.
 */
@JsonAdapter(MatchTrialStatus.Adapter.class)
public enum MatchTrialStatus {
  
  EVALUATING("evaluating"),
  
  EVALUATOR_FAILED("evaluator_failed"),
  
  SCORER_FAILED("scorer_failed"),
  
  SCORING("scoring"),
  
  SUCCESS("success");

  private String value;

  MatchTrialStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MatchTrialStatus fromValue(String value) {
    for (MatchTrialStatus b : MatchTrialStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MatchTrialStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final MatchTrialStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MatchTrialStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MatchTrialStatus.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    MatchTrialStatus.fromValue(value);
  }
}

