/*
 * OptHub REST API
 * OptHubの公開REST APIです。
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * 参加者の種別
 */
@JsonAdapter(ParticipantType.Adapter.class)
public enum ParticipantType {
  
  USER("User"),
  
  TEAM("Team");

  private String value;

  ParticipantType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ParticipantType fromValue(String value) {
    for (ParticipantType b : ParticipantType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ParticipantType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ParticipantType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ParticipantType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ParticipantType.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    ParticipantType.fromValue(value);
  }
}

