/*
 * OptHub REST API
 * OptHubの公開REST APIです。
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: dev@opthub.ai
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateSolutionResponse;
import org.openapitools.client.model.Solution;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SolutionApi
 */
@Disabled
public class SolutionApiTest {

    private final SolutionApi api = new SolutionApi();

    /**
     * 解の作成
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createSolutionTest() throws ApiException {
        UUID matchId = null;
        Object variable = null;
        CreateSolutionResponse response = api.createSolution(matchId, variable);
        // TODO: test validations
    }

    /**
     * 解の取得
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getSolutionTest() throws ApiException {
        UUID matchId = null;
        UUID participantId = null;
        Integer trialNo = null;
        Solution response = api.getSolution(matchId, participantId, trialNo);
        // TODO: test validations
    }

}
