openapi: 3.0.3
info:
  contact:
    email: dev@opthub.ai
  description: OptHubの公開REST APIです。
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  termsOfService: https://example.com/todo/opthub-api-term-of-service
  title: OptHub REST API
  version: 0.1.0
servers:
- url: https://example.com/todo/opthub-api-endpoint
tags:
- description: 解に関する操作
  name: solution
- description: 過去コンペティションへのアクセス
  name: analyzer
- description: コンペティションに関する操作
  name: competition
- description: 競技に関する操作
  name: match
- description: エイリアスに関する操作
  name: alias
paths:
  /competition/alias/{alias}:
    get:
      operationId: resolveCompetitionIdByAlias
      parameters:
      - description: コンペティションのエイリアス
        explode: false
        in: path
        name: alias
        required: true
        schema:
          $ref: '#/components/schemas/CompetitionAlias'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionId'
          description: Successful operation
        default:
          description: successful operation
      security:
      - ApiKeyAuth: []
      summary: コンペティションのエイリアスからコンペティションIDを取得
      tags:
      - competition
      - alias
      x-accepts:
      - application/json
  /competition/{id}/alias:
    get:
      operationId: resolveCompetitionAliasById
      parameters:
      - description: コンペティションのID
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/CompetitionId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionAlias'
          description: Successful operation
        default:
          description: successful operation
      security:
      - ApiKeyAuth: []
      summary: コンペティションIDからコンペティションのエイリアスを取得
      tags:
      - competition
      - alias
      x-accepts:
      - application/json
  /competition/match/alias/{alias}:
    get:
      operationId: resolveMatchIdByAlias
      parameters:
      - description: 競技のエイリアス
        explode: false
        in: path
        name: alias
        required: true
        schema:
          $ref: '#/components/schemas/MatchAlias'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchId'
          description: Successful operation
        default:
          description: successful operation
      security:
      - ApiKeyAuth: []
      summary: 競技のエイリアスから競技IDを取得
      tags:
      - match
      - alias
      x-accepts:
      - application/json
  /competition/match/{matchId}/alias:
    get:
      operationId: resolveMatchAliasById
      parameters:
      - description: 競技のID
        explode: false
        in: path
        name: matchId
        required: true
        schema:
          $ref: '#/components/schemas/MatchId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchAlias'
          description: Successful operation
        default:
          description: successful operation
      security:
      - ApiKeyAuth: []
      summary: 競技IDから競技のエイリアスを取得
      tags:
      - match
      - alias
      x-accepts:
      - application/json
  /competition/match/{matchId}/solution:
    get:
      operationId: getSolution
      parameters:
      - description: 競技のID
        example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        explode: false
        in: path
        name: matchId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: 参加者のID
        explode: true
        in: query
        name: participantId
        required: true
        schema:
          $ref: '#/components/schemas/ParticipantId'
        style: form
      - description: 試行番号
        explode: true
        in: query
        name: trialNo
        required: true
        schema:
          example: 4
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Solution'
          description: Successful operation
        default:
          description: successful operation
      security:
      - ApiKeyAuth: []
      summary: 解の取得
      tags:
      - solution
      x-accepts:
      - application/json
    post:
      operationId: createSolution
      parameters:
      - description: 競技のID
        example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        explode: false
        in: path
        name: matchId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      - description: 解空間の変数
        explode: true
        in: query
        name: variable
        required: true
        schema:
          example:
          - 1.234
          - -5.678
          - 9.1011
          items:
            format: double
            type: number
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSolutionResponse'
          description: Successful operation
        default:
          description: successful operation
      security:
      - ApiKeyAuth: []
      summary: 解の作成
      tags:
      - solution
      x-accepts:
      - application/json
components:
  schemas:
    CreateSolutionResponse:
      description: 解の作成リクエストの結果
      example:
        trialNo: 4
        participant:
          participantId: 912f548d-2bbe-48ab-90ce-e96dae38377d
          participantType: User
      properties:
        participant:
          $ref: '#/components/schemas/Participant'
        trialNo:
          description: 試行番号
          example: 4
          format: int32
          type: integer
      required:
      - participantId
      - participantType
      - trialNo
      type: object
    Solution:
      description: 解
      example:
        createdAt: 2024-08-06T10:11:45.789Z
        trialNo: 4
        variable:
        - 1.234
        - -5.678
        - 9.1011
        userId: 1e892e70-47ba-4c8e-8563-6aea9019e334
        matchId: 5d7fc778-3e59-4128-a797-2e423c0aa461
        participant:
          participantId: 912f548d-2bbe-48ab-90ce-e96dae38377d
          participantType: User
      properties:
        matchId:
          description: 競技のID
          example: 5d7fc778-3e59-4128-a797-2e423c0aa461
          format: uuid
          type: string
        participant:
          $ref: '#/components/schemas/Participant'
        trialNo:
          description: 試行番号
          example: 4
          format: int32
          type: integer
        variable:
          description: 解空間の変数
          example:
          - 1.234
          - -5.678
          - 9.1011
          items:
            format: double
            type: number
          type: array
        createdAt:
          description: 作成日時
          example: 2024-08-06T10:11:45.789Z
          format: date-time
          type: string
        userId:
          description: 作成したユーザのID
          example: 1e892e70-47ba-4c8e-8563-6aea9019e334
          format: uuid
          type: string
      required:
      - createdAt
      - matchId
      - participantId
      - participantType
      - trialNo
      - variable
      type: object
    Participant:
      description: 参加者の情報
      example:
        participantId: 912f548d-2bbe-48ab-90ce-e96dae38377d
        participantType: User
      properties:
        participantId:
          description: 参加者のID
          example: 912f548d-2bbe-48ab-90ce-e96dae38377d
          format: uuid
          type: string
        participantType:
          $ref: '#/components/schemas/ParticipantType'
      required:
      - participantId
      - participantType
      type: object
    ParticipantId:
      description: 参加者のID
      example: 912f548d-2bbe-48ab-90ce-e96dae38377d
      format: uuid
      type: string
    ParticipantType:
      description: 参加者の種別
      enum:
      - User
      - Team
      example: User
      type: string
    CompetitionId:
      description: コンペティションのID
      example: 42c999a1-a30c-47ef-b656-eb49f67488dc
      format: uuid
      type: string
    CompetitionAlias:
      description: コンペティションのエイリアス
      example: competition123
      type: string
    MatchId:
      description: 競技のID
      example: 5d7fc778-3e59-4128-a797-2e423c0aa461
      format: uuid
      type: string
    MatchAlias:
      description: 競技のエイリアス
      example: match123
      type: string
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey

