openapi: 3.0.3
info:
  contact:
    email: dev@opthub.ai
  description: OptHub Public REST API.
  license:
    name: MIT
    url: https://opensource.org/license/mit/
  termsOfService: https://example.com/todo/opthub-api-term-of-service
  title: OptHub REST API
  version: 0.1.1
servers:
- url: https://example.com/todo/opthub-api-endpoint
tags:
- description: Operations about solution.
  name: solution
- description: Access to past competitions.
  name: analyzer
- description: Operations about competition.
  name: competition
- description: Operations about match.
  name: match
- description: Operations about participant.
  name: participant
- description: Operations about alias.
  name: alias
paths:
  /competition/alias/{alias}:
    get:
      operationId: resolveCompetitionIdByAlias
      parameters:
      - description: Competition alias
        example: competition123
        explode: false
        in: path
        name: alias
        required: true
        schema:
          $ref: '#/components/schemas/CompetitionAlias'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionId'
          description: Competition ID
        "404":
          description: Competition not found
      security:
      - ApiKeyAuth: []
      summary: Retrieve the competition ID from the competition alias
      tags:
      - competition
      - alias
      x-accepts:
      - application/json
  /competition/{id}/alias:
    get:
      operationId: resolveCompetitionAliasById
      parameters:
      - description: Competition ID
        example: 42c999a1-a30c-47ef-b656-eb49f67488dc
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/CompetitionId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompetitionAlias'
          description: Competition alias
        "404":
          description: Competition not found
      security:
      - ApiKeyAuth: []
      summary: Retrieve the competition alias from the competition ID
      tags:
      - competition
      - alias
      x-accepts:
      - application/json
  /competition/match/alias/{alias}:
    get:
      operationId: resolveMatchIdByAlias
      parameters:
      - description: Match alias
        example: match123
        explode: false
        in: path
        name: alias
        required: true
        schema:
          $ref: '#/components/schemas/MatchAlias'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchId'
          description: Match ID
        "404":
          description: Match not found
      security:
      - ApiKeyAuth: []
      summary: Retrieve the match ID from the match alias
      tags:
      - match
      - alias
      x-accepts:
      - application/json
  /competition/match/{matchId}/alias:
    get:
      operationId: resolveMatchAliasById
      parameters:
      - description: Match ID
        example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        explode: false
        in: path
        name: matchId
        required: true
        schema:
          $ref: '#/components/schemas/MatchId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatchAlias'
          description: Match alias
        "404":
          description: Match not found
      security:
      - ApiKeyAuth: []
      summary: Retrieve the match alias from the match ID
      tags:
      - match
      - alias
      x-accepts:
      - application/json
  /competition/match/{matchId}/solution:
    get:
      operationId: getSolution
      parameters:
      - description: Match ID
        example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        explode: false
        in: path
        name: matchId
        required: true
        schema:
          $ref: '#/components/schemas/MatchId'
        style: simple
      - description: Participant ID
        example: 912f548d-2bbe-48ab-90ce-e96dae38377d
        explode: true
        in: query
        name: participantId
        required: true
        schema:
          $ref: '#/components/schemas/ParticipantId'
        style: form
      - description: Trial number
        explode: true
        in: query
        name: trialNo
        required: true
        schema:
          example: 4
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Solution'
          description: Information of the solution
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSolutionError'
          description: The created solution specified in the query was not found
      security:
      - ApiKeyAuth: []
      summary: Retrive solution
      tags:
      - solution
      x-accepts:
      - application/json
    post:
      operationId: createSolution
      parameters:
      - description: Match ID
        example: 5d7fc778-3e59-4128-a797-2e423c0aa461
        explode: false
        in: path
        name: matchId
        required: true
        schema:
          $ref: '#/components/schemas/MatchId'
        style: simple
      - description: Solution space variable
        explode: true
        in: query
        name: variable
        required: true
        schema:
          example:
          - 1.234
          - -5.678
          - 9.1011
          items:
            format: double
            type: number
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSolutionResponse'
          description: Information of the created solution
        "404":
          description: Match not found
      security:
      - ApiKeyAuth: []
      summary: Create solution
      tags:
      - solution
      x-accepts:
      - application/json
  /participant/{id}:
    get:
      operationId: getParticipant
      parameters:
      - description: Participant ID
        example: 912f548d-2bbe-48ab-90ce-e96dae38377d
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/ParticipantId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Participant'
          description: Participant information
        "404":
          description: Participant not found
      security:
      - ApiKeyAuth: []
      summary: Retrieve the participant information
      tags:
      - participant
      x-accepts:
      - application/json
components:
  schemas:
    CreateSolutionResponse:
      description: Information of the created solution
      example:
        participantId: 912f548d-2bbe-48ab-90ce-e96dae38377d
        trialNo: 4
      properties:
        participantId:
          description: Participant ID
          example: 912f548d-2bbe-48ab-90ce-e96dae38377d
          format: uuid
          type: string
        trialNo:
          description: Trial number
          example: 4
          format: int32
          type: integer
      required:
      - participantId
      - trialNo
      type: object
    Solution:
      description: Solution information
      example:
        createdAt: 2024-08-06T10:11:45.789Z
        variable:
        - 1.234
        - -5.678
        - 9.1011
        userId: 1e892e70-47ba-4c8e-8563-6aea9019e334
      properties:
        variable:
          description: Solution space variable
          example:
          - 1.234
          - -5.678
          - 9.1011
          items:
            format: double
            type: number
          type: array
        createdAt:
          description: Creation date and time
          example: 2024-08-06T10:11:45.789Z
          format: date-time
          type: string
        userId:
          description: ID of the user who created it
          example: 1e892e70-47ba-4c8e-8563-6aea9019e334
          format: uuid
          type: string
      required:
      - createdAt
      - variable
      type: object
    GetSolutionError:
      description: Failed to retrieve the solution
      enum:
      - InvalidMatchId
      - InvalidParticipantId
      - TrialNotFound
      type: string
    Participant:
      description: Participant information
      example:
        participantType: User
      properties:
        participantType:
          $ref: '#/components/schemas/ParticipantType'
      required:
      - participantType
      type: object
    ParticipantId:
      description: Participant ID
      example: 912f548d-2bbe-48ab-90ce-e96dae38377d
      format: uuid
      type: string
    ParticipantType:
      description: Participant type
      enum:
      - User
      - Team
      example: User
      type: string
    CompetitionId:
      description: Competition ID
      example: 42c999a1-a30c-47ef-b656-eb49f67488dc
      format: uuid
      type: string
    CompetitionAlias:
      description: Competition alias
      example: competition123
      type: string
    MatchId:
      description: Match ID
      example: 5d7fc778-3e59-4128-a797-2e423c0aa461
      format: uuid
      type: string
    MatchAlias:
      description: Match alias
      example: match123
      type: string
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: x-api-key
      type: apiKey

